
pipeline {
    
    agent any {
	    docker { image 'python3' }
	}
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git branch: 'main', 
				url: 'https://github.com/kamalakar22/Jenkins-Zero-To-Hero.git'
                
           }
        }

        stage('Docker Login') {
           steps {
               script {
                   // Login to Docker Hub
                   docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
                       // This block will automatically log out after it finishes
                       echo 'Logged in to Docker Hub'
                    }
                }
            }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    echo 'Buid Docker Image'
                    docker build -t gundala22reddy/cicd:${BUILD_NUMBER} .
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    sh '''
                    echo 'Push to Repo'
                    docker push gundala22reddy/cicd:${BUILD_NUMBER}
                    '''
                }
            }
        }
       
    }
}
