pipeline {
    agent {
        docker {
            image 'python:3'
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout') {
            steps {
                git branch: 'main', 
                url: 'https://github.com/kamalakar22/Jenkins-Zero-To-Hero.git'
            }
        }

        stage('Docker Login') {
            steps {
                script {
                    // Login to Docker Hub if needed
                    // docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
                    //     // This block will automatically log out after it finishes
                    //     echo 'Logged in to Docker Hub'
                    // }
                    // This step may not be necessary if the image is publicly available
                }
            }
        }

        stage('Build Docker') {
            steps {
                script {
                    echo 'Build Docker Image'
                    sh "docker build -t gundala22reddy/cicd:${BUILD_NUMBER} ."
                }
            }
        }

        stage('Push the artifacts') {
            steps {
                script {
                    echo 'Push to Repo'
                    sh "docker push gundala22reddy/cicd:${BUILD_NUMBER}"
                }
            }
        }
       
    }
}
